### ISSUE TITLE
Sporadic failures on /pins endpoint

### ISSUE THREAD

**Issue by 3456091** [web3-storage/web3.storage#1167]
When using go-ipfs to pin CIDs with large payloads, web3.storage is continually polled. After many polls, it often returns an error, which aborts the pin request. I've included the requestIDs in the example below in case they help with debugging.

```
$ ipfs pin remote add --name=blah bafy... --service=w3s
Error: failed to check pin status for requestid="3714a518-2c90-4578-b0e7-e884de723ec7" due to error: reason: "", details: "": 404 Not Found
$ ipfs pin remote add --name=blah bafy... --service=w3s
Error: failed to check pin status for requestid="bbbf1b5d-cb1b-48ce-8f39-a33c1a0d48ce" due to error: reason: "", details: "": 500 Internal Server Error
$ ipfs pin remote add --name=blah bafy... --service=w3s
Error: failed to check pin status for requestid="3048fd27-b3d9-45ce-b8b5-dbacc63d4cfa" due to error: reason: "", details: "": 500 Internal Server Error
```

**Comment by 3456091** [comment]
Yes, that specific CID is pinned now, but the symptoms persisted for a while.

**Comment by flea89** [comment]
> I've just encountered this again with a test file. I uploaded a tiny CAR, then polled the /pins/$requestID endpoint for a status change as the go-ipfs client does. After about 6 minutes that returned 404. Now that same URL returns "{"reason":"PSA_RESOURCE_NOT_FOUND","details":"Requested data was not found."}".

@3456091 could you please give us some more context what you mean by `I uploaded a tiny CAR` ?
Have you done that by sending a POST request to `/pins` like documented [here](https://ipfs.github.io/pinning-services-api-spec/#tag/pins/paths/~1pins/post)? 
Was the response a 200 in the first place?

@3456091 Please let us know if you experience more issues with the APIs and we'll look into it. And thanks for reporting them in the first place.

> @flea89 any ideas on the root reason for this?

Unfortunately nothing evident I can see here, I wonder if the initial issue you reported in your first comment were due to an invalid key being used to authorize the request.

**Comment by 3456091** [comment]
@flea89 Yes, I POSTed to the /pins endpoint, both using curl and ipfs-go. The status was initially 200, as where many of the subsequent requests to the same endpoint to check the status; at some indeterminate point a bad status was returned. For ipfs-go, this aborts the polling loop.
