### ISSUE TITLE
feat: email a user when their account is restricted/derestricted or their quota is increased

### ISSUE THREAD

**Issue by adamalton** [web3-storage/web3.storage#1199]
Whenever we:
* Restrict a user's account
* Derestrict a user's account (if we ever do that)
* Increase a user's quota
we should send them an email to inform them.

This probably depends on #1195 and #1153.

**Comment by JeffLowe** [comment]
Will need to keep this one scoped only to web3 storage limit notifications.  We do not need emailed notifications when a user's account is blocked/unblocked, or api token is blocked/unblocked.

**Comment by dchoi27** [comment]
Yeah just following up here - right now the main reason we block folks' accounts is because they're uploading illegal content. ATM letting them know they've been blocked isn't really helpful - if anything it might encourage them just to make a new account.

**Comment by adamalton** [comment]
Thanks both. Closing this.

**Comment by flea89** [comment]
Actually, we think that some of the use cases mentioned might benefit from emailing the user.

When the account restriction feature will be released we will start restricting users because of storage usage as well as for illegal content. 
In the case of restricting because of storage usage, emailing those users might make sense and improve the overall user experience.

Given that in the API we are already giving a user a message when their actions are restricted to explain the reason we believe we can launch the MVP without these emails.

But we'd like to keep this open to discuss this further and consider it for future iterations.

**Comment by dchoi27** [comment]
Yeah that makes sense to me!
