### ISSUE TITLE
524 CloudFlare errors with status code 500 and 503 from API

### ISSUE THREAD

**Issue by DonaldJimenez** [web3-storage/web3.storage#1315]
I experimented with API endpoint `/car` uploading several Gb in ~95mb chunks. After about 1 Gb of traffic I start occasionally receiving 500 status. It looks like some sort of rate limit from CloudFlare proxy protecting the API.

I saw three types of responses. Two return 500 status code and JSON:
`{"code":"HTTP_ERROR","message":"524: Origin Time-out"}`
`{"code":"HTTP_ERROR","message":"524: "}`

Third returns 503 and CloudFlare HTML page

`<title>Worker exceeded resource limits | api.web3.storage | Cloudflare</title></title>`

Text suggests logging in CloudFlare account and checking error logs.

Currently, the docs only mention rate limit with response code 429. I'm certainly not hitting 30 requests within 10 seconds. I use some bandwidth, though. My script starts next 95 Mb `/car` POST sequentially as soon as previous one returns 200 response. Each request takes about 1 minute on its own, far from hitting rate limits. After 5xx my script waits 60 seconds before retry. This setup failed to upload more than ~6 GB of data, eventually hitting a wall of constant 500 errors. Restart in several hours of idle again uploads 1 Gb before starting to receive first 500s.

This does not look intended. If it is, I think it is a good idea to mention this behavior in HTTP API docs. Or investigate further if it's not.

**Comment by adamalton** [comment]
Hi @DonaldJimenez 

We think that these errors are probably being caused by the ~95mb chunk size. Our recommendation is to use the JS client library. This will use chunk sizes of ~10mb, but will do some parallelisation so won't be as slow as that might imply.

The 524 errors are most likely being caused by the IPFS cluster timing out, which again will probably be helped by a smaller chunk size.

The 503 Cloudflare errors are most likely being caused by our API endpoint (which is a Cloudflare Worker) hitting its 100mb memory limit. With a 95mb upload size, as we process that it will push the memory usage over 100mb.

We'll update the docs with a note about this.
