### ISSUE TITLE
Disabled writes affect logging in

### ISSUE THREAD

**Issue by vasco-santos** [web3-storage/web3.storage#1433]
Noticed that when we set maintenance mode to read only, website log ins are also affected after https://github.com/web3-storage/web3.storage/pull/1271

Login route is `POST /user/login`, and POST requests are disabled on write disabled. We need a special case for log in

**Comment by olizilla** [comment]
To add a little more detail the problem is we simplified how we configure READ-ONLY mode in the router by applying a catch-all handler on POST. The intention here was to encourage us to use the correct http verbs for actions that change state.

https://github.com/web3-storage/web3.storage/blob/f445cda5da6fef3893bb291bce61f42f02506927/packages/api/src/index.js#L27-L30

Our login method is a POST, and we combine login and sign up into a single path. Inside the loginOrRegister method we call `db.upsert` to update or insert a user record. As such the code is now doing "the right thing™️" as we probably don't want writes or updates ot the user table while we're doing amore significant db migration.

https://github.com/web3-storage/web3.storage/blob/f445cda5da6fef3893bb291bce61f42f02506927/packages/api/src/user.js#L45

If we want to allow logins during a READ_ONLY maintenance window, then we to decide if we are ok with not updating the user table during login.
