### ISSUE TITLE
Pinning via Pinning Services API does not update the storage used

### ISSUE THREAD

**Issue by shomix** [web3-storage/web3.storage#1449]
Pinning CIDs ( that already exist on IPFS ) using the Pinning Services API does not update the storage used shown on the UI.

Scenario:
1) Open [Web3 Storage](https://web3.storage/account/) and take a look at the storage used. Let's say that storage used is equal X.
2) Using the Pinning Services API, pin some CID that was uploaded with some other service.
- example request:
```
curl -X POST 'https://api.web3.storage/pins' \
  --header 'Accept: */*' \
  --header 'Authorization: Bearer <YOUR_AUTH_KEY_JWT>' \
  --header 'Content-Type: application/json' \
  -d '{
  "cid": "Qmd1ayqBjPZ424CRJzUHJXDYCXXXayYLgReWvvUXD53VGf",
  "name": "web3-storage-example"
}'
```
3) The storage used, that is shown on the UI does not get updated, and has the same value X as from the step 1. 
Using the request bellow, I have checked the status of the CID sent in request ( 3from the second step ), and it's status is `pinned`.
```
curl -X GET 'https://api.web3.storage/pins?status=pinned,queued,pinning&cid=Qmd1ayqBjPZ424CRJzUHJXDYCXXXayYLgReWvvUXD53VGf' \
  --header 'Accept: */*' \
  --header 'Authorization: Bearer <YOUR_AUTH_KEY_JWT>'
```

**Comment by mbommerez** [comment]
Thanks, we are looking into this.

**Comment by flea89** [comment]
@shomix thanks for reporting this.

We had an issue where dag sizes were not populated correctly, which should now be fixed and work for new pins.
We'll run a job to fix historical data (hopefully by end of the week). Once that happened the storage used will update to reflect all your pin requests.

Please be aware that, for the Pinning APIs, there might be some lead time from when you see a request as "pinned" and the size and storage to be updated, since the dag size is fetched asynchronously. It might take up to 90 minutes.

We might consider changing that to have a better user experience, but for now, that's how it works.

Please let us know if this is still a problem while pinning new files. 🙏

**Comment by flea89** [comment]
## Note
Also worth adding that having to fetch the size for all psa_request is affecting the performance of our job. One more reason to go for getting the size independently when "pinned"

**Comment by mbommerez** [comment]
Closing this ticket.
@shomix please let us know if you notice any other occurrences in the future.
