### ISSUE TITLE
Website alignment bug on microsoft edge mobile

### ISSUE THREAD

**Issue by mehulagg** [web3-storage/web3.storage#154]
![20210724_130510](https://user-images.githubusercontent.com/53606356/126861230-bdfcd0a2-8fcd-4847-9dc5-82c3f3afad1b.jpg)

**Comment by alanshaw** [comment]
resolved by https://github.com/web3-storage/web3.storage/pull/157 - please shout if still broken!

**Comment by mehulagg** [comment]
@alanshaw still broken!

![20210726_104120](https://user-images.githubusercontent.com/53606356/126936361-2110afae-8d83-4333-815c-f583b3d95acc.jpg)

**Comment by alanshaw** [comment]
yep thanks

**Comment by alanshaw** [comment]
@jdiogopeixoto I tried to fix this quickly last night but failed. Safari does not understand `overflow: clip` so I used `CSS.supports` to detect support and do somethiing else. This doesn't work on first render though (because first render is done on the server) and it doesn't get re-rendered on the client. I missed that in dev because of the auto reload 🤦 .

**Comment by rafaelramalho19** [comment]
@alanshaw thank god my old ie11 fallback experience is useful for something now 😄 

Fixed with
```css
const style = { overflowX: 'clip' , overflow: 'hidden' }
```

If the browser doesn't support 'clip', it gets unrecognized and ignored, meaning that `overflow: hidden:` gets applied. On all modern browsers `overflow-x: clip` just overrides `overflow: hidden` 😄
