### ISSUE TITLE
Improve error handling and user feedback

### ISSUE THREAD

**Issue by JeffLowe** [web3-storage/web3.storage#1552]
#1318 is one example of improvements underway to error feedback.  We need further coverage throughout site.  
- [ ] ensure error like the one reported in #1235 provides user feedback in UI better explaining failure
- [ ] explore key flows and look for opportunities to improve error handling and user feedback

**Comment by e-schneid** [comment]
@JeffLowe My understanding of the issue is that the file uploader just displays "Failed."  The change I've applied is pretty simple but I think it should satisfy the requirements here.  It will now also have a tooltip icon next to "Failed," and when hovering over the icon it'll display the error message that we get back from the API for that specific file.

https://bafybeiccbyv5brqc35on75sheat2xrkwc2x7fomy36qvkxjn3kxa5lhnqi.ipfs.nftstorage.link/ for the PR deployment of this change.
