### ISSUE TITLE
https://web3.storage/account/  Clicking on CID triggers virus checkers to complain about blacklisted URLs

### ISSUE THREAD

**Issue by javaspeak** [web3-storage/web3.storage#1775]
Clicking on CID in https://web3.storage/account/  results on virus checkers complaining about blacklisted URLs

This is a new event - something has changed.

URLs like:

     https://w3s.link/ipfs/bafybeidppu7riyqtfaefhxja42yajgoin7yhki57zkpiu2akxflhzdg73q

are now blacklisted.

See attached image.

<img width="1096" alt="Screenshot 2022-08-22 at 11 20 52" src="https://user-images.githubusercontent.com/26520180/185874575-103191e3-c2cb-46a1-b44b-c946418fe3d4.png">

Does anyone know what is going on here?

Thank you

**Comment by javaspeak** [comment]
Note that 2 days before the AVG virus checker complained about the url, the Chrome Browser was complaining about it and saying the URL was black listed.

**Comment by dchoi27** [comment]
Thanks - since w3s.link is relatively new, when users are accessing malicious content through it, security vendors are probably blocking the entire domain rather than the specific subdomains corresponding with malicious content. I filed a false positive request here, and I'm sure it'd be helpful if you do as well https://www.avg.com/en-us/false-positive-file-form

Could you share a URL that Google Chrome is flagging? I can reach out to that team as well if we have examples.

One note - you can always change the gateway you're using to the dweb.link in the top right corner of your uploads table.

**Comment by javaspeak** [comment]
> Could you share a URL that Google Chrome is flagging? I can reach out to that team as well if we have examples.

AVG has stopped blocking the urls. 

Chrome Browser is also no longer blocking the urls.  

Your false positive request worked.

Thanks
