### ISSUE TITLE
Fix breadcrumbs for "products" pages

### ISSUE THREAD

**Issue by JeffLowe** [web3-storage/web3.storage#1926]
Breadcrumbs currently do not show for any of the product pages.  Update site to ensure that breadcrumbs work /display for these pages.  

- [x] update breadcrumbs to reflect the correct product page
- [ ] update the tab title (currently shows "About - web3.storage"

We should likely show the following in the breadcrumbs:

- "Home / Products / Web3.Storage" (when on https://web3.storage/products/web3storage/ )
- "Home / Products / w3name" (when on https://web3.storage/products/w3name/ )
- "Home / Products / w3link" (when on https://web3.storage/products/w3link/ )

## Current breadcrumbs for Products page
![Screen Shot 2022-09-22 at 11 21 53 AM](https://user-images.githubusercontent.com/2078567/191800806-ed19e66b-3f8e-486c-8469-77574885ab61.png)

## Example breadcrumbs for FAQ page (for reference)
![Screen Shot 2022-09-22 at 11 19 43 AM](https://user-images.githubusercontent.com/2078567/191800837-1aebc219-d51a-438e-92d4-e208ebc2b8db.png)

## example of the tab title when on products page

![Image](https://user-images.githubusercontent.com/2078567/192035727-065f68e8-fe51-4c52-961b-8ee81959526f.png)

**Comment by e-schneid** [comment]
@JeffLowe I just wanted to call out that since we don't have a "Products" route (i.e., https://web3.storage/products), my current fix in PR is to add the crumbs "Home / w3link", "Home / Web3.Storage" and "Home / w3name".  Let me know if this works.  The hierarchy on the site is a little unusual, so it's not super obvious what's correct.  

The crumbs may also be a bit off for the pages under Account as well (for example, the tokens screen should possibly have the crumbs "Home / Account / API Tokens", etc), but I've held off on changes for those for now, since we may need to do a general sweep of all crumbs and see which ones need to be cleaned up.  I've refactored our breadcrumbs so it should be easier to configure them if we want to make some more changes.

**Comment by JeffLowe** [comment]
That seems acceptable for the crumbs ( eg Home / w3link). @dchoi27 let us know if we need to reconsider that approach.  

THANK YOU for the refactor and thinking of ease of maintaining for future.  
Regarding the accounts page(s) I see your concern.  I think it's acceptable to leave it as is for now, but feel free to override me if there is a concern @dchoi27

**Comment by dchoi27** [comment]
Works for me!
