### ISSUE TITLE
Hydration of nav is very slow

### ISSUE THREAD

**Issue by atopal** [web3-storage/web3.storage#195]
When I load web3.storage as a logged-in user after some time away, the dynamic nav items (files, profile, etc) appear multiple seconds after the static nav items.

**Comment by johnnymatthews** [comment]
This is a similar situation when you visit the homepage for the first time (see gif)

![login-button-slow-to-show](https://user-images.githubusercontent.com/9611008/127365332-c1749ef2-cb92-4fab-ba0a-0726d8ea0ab2.gif)

**Comment by alanshaw** [comment]
The issue is that it takes a long time for magic.link to determine if the user is logged in:

<img width="1492" alt="Screenshot 2021-08-16 at 11 41 03" src="https://user-images.githubusercontent.com/152863/129554186-269c48ed-e69b-4d7d-97cf-63bd2dbc3f7d.png">

In that profile the 3 synchronous requests take:

1. https://auth.magic.link/send - 682ms
2. https://api.magic.link/v2/auth/user/info/retrieve - 280ms
3. https://cognito-identity.us-west-2.amazonaws.com/ - 479ms

Total: 1.4s

https://github.com/web3-storage/web3.storage/pull/352 should help this (the last two requests were being repeated twice).

**Comment by atopal** [comment]
handled by now hydrating :)
