### ISSUE TITLE
Web3.storage user home page info error

### ISSUE THREAD

**Issue by yanjh007** [web3-storage/web3.storage#2064]
Hi guys, I used to use the web3.storage well in last month, and I upload some content to my account using the w3 cli tools. But recently i found some issues, after login, I cannot check my account usage status,  the homepage of my user information is :
Your Plan: Early Adopter
Storage: 0 B of 1 TiB used
and the file list is always in loading. 
In fact ,  I have already send hundred gigabytes of files to the ipfs network through w3. And, in same time, I cannot use the w3 cli tools to upload my backup files. It's always said that the api request timeout.
I dont know what happened to my account, and what I should to do, anybody could help me to check this? Please,  Thanks.

**Comment by heyjay44** [comment]
Thank you for taking the time to raise this issue and apologies for the inconvenience it has caused. Although the web3.storage service is fully functional (i.e., files can be uploaded, are persisted, and are shown in your list of uploads), we have noticed that total storage usage data isn’t properly loading for all users in the dashboard.

We are pursuing a fix. If you are on a paid plan and over your allotted storage capacity, you will not be charged for any additional storage fees (i.e., just the base cost of your subscription) until this issue is fixed.

**Comment by yanjh007** [comment]
Thanks for your feedback. I am waiting for your good news. An other question, are there some network performance limit while put file by w3 cli tools, or your server is too busy recently to handle put request, I mean, there are only on gateway api.web3.storage and not configurable in w3 cli or sdk ?

**Comment by heyjay44** [comment]
We merged a change that should address the issue you flagged with account usage [2069](https://github.com/web3-storage/web3.storage/pull/2069). Have you noticed an improvement?

**Comment by heyjay44** [comment]
Closing this issue. Please reach out if you have any questions.
