### ISSUE TITLE
Improve how we communicate what contributes to the storage quota to users

### ISSUE THREAD

**Issue by mbommerez** [web3-storage/web3.storage#2081]
## Challenge
Once we merge #2069 we will start counting failed/incompleted uploads toward the calculated storage quota for a user. These failed uploads are shown in the table.
This might not be obvious to users, and, I wonder if  the paid plans makes this a bit more sensitive.

## Suggested solution 
Let's add a tooltip to explain to the user what accrues to the total, making sure they are aware that our current storage calculation also includes incompleted uploads.

### Suggested copy
```
This is the total of all your uploads, including the ones that never completed.
You can remove uploads via the table below, through your preferred client library, the CLI or the HTTP APIs.
```
We tried to keep it as compact as possible, given this goes into a  tooltip.

### How it looks in place 
Here's a screenshot of how this could look in the dashboard

![Image](https://user-images.githubusercontent.com/3163684/200828585-18d8b602-469a-477a-ba60-d6b7feef5430.png)

### Questions
We are wondering if we should suggest to users to reach out if they need help with bulk deletion, given there's no trivial way to do it with the APIs right now.
It could be something along the lines of:
```
Please get in touch with support@web3.storage if you need bulk deleting files.
```

At the same time, not sure if that's required and might create more work for you @dchoi27 

What do you think?

Follow up on #2033

**Comment by mbommerez** [comment]
Let's add a warning / tooltip for user to be aware that our current storage calculation also includes failed uploads. And add 'Please contact support if you need help with removing those'.

**Comment by dchoi27** [comment]
Hey - I think the thought here is fine, though we're trying to move away from telling the user when their upload is "completed" since in the future they could be uploading partial graphs on purpose. I'd make the copy say something more like This is the total of all your uploads, including ones marked "Failed" (you can read more about what the status means [here](https://web3.storage/docs/how-tos/get-status/). You can remove uploads via the table below, through your preferred client library, the CLI or the HTTP APIs.

Definitely don't want to tell them to reach out if they need to bulk delete files though (let's actually remove this from the issue).
