### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR for `<CID>.ipfs.w3s.link` links

### ISSUE THREAD

**Issue by dennis-tra** [web3-storage/web3.storage#2182]
I get an `ERR_SSL_PROTOCOL_ERROR` error when clicking on the CID link in the files list:

<img width="685" alt="Screenshot 2023-01-08 at 12 18 42" src="https://user-images.githubusercontent.com/11836793/211193274-a5145ce4-a870-42f1-bb1c-24ef732da8cf.png">

**Comment by vasco-santos** [comment]
Hey @dennis-tra 

Thanks for reaching out. Sadly, we have some back and forth with some security vendors who sometimes flag w3link as malicious. You can read more about this at https://blog.nft.storage/posts/2022-04-29-gateways-and-gatekeepers

Per the above, this is likely the ISP being used blocking the domain based on a security list they follow. Could you let us know your ISP so that we can try to get it unblocked (feel free to send an email to `support@web3.storage` for privacy)? If you can also report to them yourself will probably help unblock this faster.

In the meantime, you will need to either use a VPN or a different internet connection. Let us know the ISP so that we can try to unblock this for everyone :)

**Comment by dennis-tra** [comment]
Hi @vasco-santos,

Thanks for the response! Interesting that it might be blocked at the ISP level. My ISP is Swisscom, so feel free to reach out to them. I'm using my own IPFS node in the meantime :)

Let me know if I should check again, or CC me if you like.

**Comment by vasco-santos** [comment]
Hey @dennis-tra 
Could you please fill in https://www.swisscom.ch/en/residential/internet/protection-security/internet-guard-details/formular.html to report?
I tried to do so, but I am required to have a swiss phone number apparently. Could not manage to submit and reached out via support chat to them. Would be great to have the form also submitted

**Comment by dennis-tra** [comment]
Sure, I just submitted the form. I'll get back here as soon as I hear from them 👍

**Comment by dennis-tra** [comment]
> Dear Sir or Madam,
>  
> Thank you for your message. We assume that the security problem on your website has been corrected by you or the provider (hoster) of the website. During our check, we could no longer detect any harmful content. We have therefore removed the Internet Guard warning message before visiting your website.
>  
> Kind regards
> Swisscom (Switzerland) AG
> Internet Guard Team

Now, it works again 👍

**Comment by vasco-santos** [comment]
@dennis-tra thanks so much for helping out
