### ISSUE TITLE
ensuring users see correct UI upon login

### ISSUE THREAD

**Issue by heyjay44** [web3-storage/web3.storage#2218]
ACs are [here](https://www.notion.so/2023-02-21-user-stories-426956932768465e926cfcefa336707a)

**Comment by heyjay44** [comment]
@gobengo I updated the ACs

**Comment by gobengo** [comment]
Great. @e-schneid do the acceptance criteria make sense to you? Can you describe some eng steps required to make a PR so the prduct meets those criteria?

**Comment by e-schneid** [comment]
@gobengo The acceptance criteria makes sense.

Since we no longer seem to care about overages and all remaining customers without subscriptions will appear identical to the free tier, I think there's just one step:

1) Update the UI so that if a customer doesn't have a subscription, display for them the Free tier.

**Comment by gobengo** [comment]
> Since it's unrelated to the AC, we may want a separate ticket to deal with the removal of the logic around automatically signing users up to the Free tier (or we can add to the existing AC -- either way works for me).

I agree. It seems like doing #1 is a prerequisite to safely remove that logic, so let's just do #1 to completion first. If that goes well, we can remove the the auto-creation logic after

**Comment by e-schneid** [comment]
Due to a race condition, a new user may end up either with a Free tier subscription in Stripe, or they may end up with no subscription at all.  We want to ensure that in either case the user will see the same UI indicating that they're Free tier users.

Steps used to validate:

1. Logged in with a user with no subscription: 84a7ebf8-647f-49fd-a000-fb794770c287@mailslurp.com
Saw result:
![image](https://user-images.githubusercontent.com/99349687/221040271-17903b86-6ed2-42f1-8b03-da478a96a0d9.png)


2. Logged in with a user with a subscription to the Free tier: 7fcba705-5c50-48bc-b733-7fce82a78ea7@mailslurp.com
Saw result:
![image](https://user-images.githubusercontent.com/99349687/221039026-98304201-fefb-4ad3-a3f8-320a652e94c6.png)

3. Verified that both results match

4. Performed manual regression against other subscription types:

#### Early Adopter 1TiB:
![image](https://user-images.githubusercontent.com/99349687/221040877-40d2f927-d033-44b2-a972-47281278b793.png)

#### Early Adopter No CC:
![image](https://user-images.githubusercontent.com/99349687/221041578-b53b4bf8-fe3a-4823-8a84-0caccb87e4e1.png)

#### Lite:
![image](https://user-images.githubusercontent.com/99349687/221041721-a2ce32fb-932c-4282-accc-64d8c2a3b8bc.png)

#### Pro:
![image](https://user-images.githubusercontent.com/99349687/221041853-c8898a4c-0179-41a1-880a-de765c679a73.png)

#### Outercore Funded:
![image](https://user-images.githubusercontent.com/99349687/221042038-34a36fee-8e91-4f13-abae-f9d3bfe4a967.png)

**Comment by gobengo** [comment]
staging

```
email       | 84a7ebf8-647f-49fd-a000-fb794770c287@mailslurp.com
id          | 315318734258473481
customer_id | cus_NPc2IR4iyOhBqs
```

```
email       | 7fcba705-5c50-48bc-b733-7fce82a78ea7@mailslurp.com
id          | 315318734258473479
customer_id | cus_NPbvSkFB4kqjXP
```

**Comment by gobengo** [comment]
reopening until we confirm in prod
