### ISSUE TITLE
Link to make a new unique account via magic.link

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#279]
Would be great to have a link that minimizes friction in making a new account. Currently the closest thing we have is linking to web3.storage/login, which takes you to this screen:
![image.png](https://images.zenhubusercontent.com/5fa04bd64afb77249c77235b/bdb2c2f9-ae69-40ad-b3ce-31165fc173f5)

This makes the user have to go through an additional step to create an account. Clicking on the Github authentication link takes the user to this link: https://auth.magic.link/v1/oauth2/credential/create. If you just paste the URL in your browser directly, you get some strange behavior (either takes them back to web3.storage or shows an infinite loading page).

Would be great to have a link that immediately takes them to the Github auth page if they don't have an account associated with their Github account already, and if they do, logs them in.

**Comment by momack2** [comment]
What about just having an email link that directly does the email signup flow? Seems easier than having to pair with their github credentials (they're already in their email, so we know it's them!)

**Comment by dchoi27** [comment]
That works too! Whatever is easier

**Comment by alanshaw** [comment]
I think people need the opportunity to decide if they want to create an account. Linking them to something that creates an account and sends them another email feels a bit sneaky. Personally that would put me off.

We could do something like send them a link to the login page with the email field pre-populated?

Alternatively, have a separate landing page with some basic information/reasons you might want to use the service along with the sign in form (pre-populated). The generic login page isn't a great place to send people from an email since it doesn't have anything to make people want to sign up.
