### ISSUE TITLE
Getting 503 errors with site

### ISSUE THREAD

**Issue by TrevorJTClarke** [web3-storage/web3.storage#350]
Tried logging in with github, callback URL had 503.
Tried creating API key, page got 503:

<img width="985" alt="Screen Shot 2021-08-13 at 8 51 00 AM" src="https://user-images.githubusercontent.com/2633184/129385744-08ca9246-ef6f-4fa7-9a5b-fd818480734b.png">

**Comment by Meowcat285** [comment]
Same here too, but its intermittent.

**Comment by olizilla** [comment]
Thanks for reporting! Pleae can you share some more details @TrevorJTClarke & @Meowcat285. Do you know the date & time that it happened. Did you raise the issue/comment right after it happened?

Are you able to grab the response headers for the request that gave you the 503 response from your browsers dev tools? Can check for an `x-ipfs-pop` header, and if you see it, share it on this thread? I Firefox it'd look like this:

<img width="1395" alt="Screenshot 2021-08-17 at 10 49 53" src="https://user-images.githubusercontent.com/58871/129704371-a725f656-d5f4-412c-8fe6-64f261c2e041.png">

The change to explore here is to host web3.storage on it's own IPFS gateway rather than leaning on the public one, which occasionally gets abused, which can cause it to respond with 503s for requests coming from the same region.

**Comment by TrevorJTClarke** [comment]
@olizilla correct, i reported directly after it happened.

Here's what im seeing now:
```
x-ipfs-gateway-host: gateway-bank2-sjc1
x-ipfs-path: /ipns/web3.storage/_next/data/6Phc-F9Dd8H9YYLg3RQoN/account.json
x-ipfs-pop: gateway-bank2-sjc1
```

Trying to create api token, and only seeing 401s, even though i am still technically logged in.

**Comment by dchoi27** [comment]
Should be fixed so closing for now, let me know if not. But #208 should help solve this in the future
