### ISSUE TITLE
Make clear in HTTP API docs that deleting a file doesn't unpin

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#376]
When a user deletes a file, we don't unpin because it might be pinned by other users. Want to make sure this is clear in the HTTP docs.

https://github.com/web3-storage/web3.storage/pull/145/files#diff-009e4858e5227329eeeb2bf592cb71338170d8b31f25b32d821d440ea238f162R111

**Comment by yusefnapora** [comment]
I'm going to close for now and pick this up when we add delete through the API.

**Comment by idmeglobally** [comment]
please  how any help me here out on how to unpin in ipfs, i used web3 storage to upload the file and i deleted the file due to error on the script, but each time i click the link i still have access to the page, please i don't want to see the file any more, what most i do to unpin it and remove it totally from the web?
