### ISSUE TITLE
Demo of UCAN based auth

### ISSUE THREAD

**Issue by atopal** [web3-storage/web3.storage#542]
Fission team developed [UCAN](https://blog.fission.codes/auth-without-backend/): System for authorizing users without a back end. We would like to do a field study by creating a demo showcasing how UCANs could enable improve our current auth system.

**Comment by olizilla** [comment]
I think their current offering is based on UCANs, but also depends on their infra. They have a proposal for an sdk that would allow apps to implement UCANs without needing to depend on their infra, but as I understand it that doesn't exist yet. The issue here is that we need someone on the team to dig in to the details of what fission offers today, and then help us make a call on if we want to adopt their proposal. This is an "explore and report back" issue. Could you take a pass at refining the scope of this issue please as you learn more.

**Comment by Gozala** [comment]
> I think their current offering is based on UCANs, but also depends on their infra. They have a proposal for an sdk that would allow apps to implement UCANs without needing to depend on their infra, but as I understand it that doesn't exist yet.

This is incorrect, there is no dependence on their infrastructure.

> The issue here is that we need someone on the team to dig in to the details of what fission offers today, and then help us make a call on if we want to adopt their proposal. This is an "explore and report back" issue. Could you take a pass at refining the scope of this issue please as you learn more.

Sure I'll post updates and change issue description

**Comment by Gozala** [comment]
https://hackmd.io/@gozala/ucan-demo
https://github.com/Gozala/ucan-demo
https://observablehq.com/d/7fb5d13d63f667b9
