### ISSUE TITLE
Delete via JS Client

### ISSUE THREAD

**Issue by hhff** [web3-storage/web3.storage#560]
Thank you so much for the hard work, team. This is a really great project! :)

It would be cool to be able to delete an upload via the client.

I assume doing this (right now from the UI) unpins the file, and it eventually vanishes from IPFS & Filecoin, right?

**Comment by insanity54** [comment]
If you need to delete a file from IPFS at some point, IPFS is probably not the right solution to your storage needs. IPFS is a public network where anybody can pin what you upload to IPFS. In that case, the content stays online even if you aren't pinning.

> Users should not use Web3.Storage for data that may need to be permanently deleted in the future.

Ref: https://web3.storage/about/

**Comment by stefanogalizia** [comment]
Hi there,
yes is correct and i am aware of this, but since in web3.storage accounts
there is 1TB limit, the delete feature is meant to free space on specific
account.

**Comment by atopal** [comment]
Unfortunately that's not possible just yet. You have to delete using the web UI, but we are working on enabling deletes through the API. In the mean time: the 1TB limit is very flexible, if you need more data, please use the link on your account page to request it.

**Comment by stefanogalizia** [comment]
Thanks @atopal , will do.

**Comment by svub** [comment]
I still get the error message that `delete` has not been implemented yet. Are there any plans to do that? 

In my situation, even just having a setting like "if the storage is full, automatically delete old files" would be sufficient. Is something like that coming? 

Because right now, without a programmatic or automatic deleting, this API is not suitable for a web app - deleting is necessary. Me regularly checking and manually deleting old files is not a viable solution.
