### ISSUE TITLE
Listing uploads through api is limited to 25

### ISSUE THREAD

**Issue by mehulagg** [web3-storage/web3.storage#598]
I am not able to get more than 25 uploads returned by `https://api.web3.storage/user/uploads?limit=100`

**Comment by alanshaw** [comment]
After the database migration work today we should be able to increase this limit.

**Comment by atopal** [comment]
just a quick update, the the migration will happen on Monday, November 15.

**Comment by atopal** [comment]
We'll update this to list 1000 records.

AC:
- [ ] change limit
- [ ] test limit
- [ ] update docs

**Comment by vasco-santos** [comment]
Just added a PR #645 to update the limit. It is worth mentioning that `limit` was not the correct parameter and should be `size`. So, if you use `size` instead of `limit` today, it is already working until 100.

I also PRd the docs https://github.com/web3-storage/web3.storage/pull/646 to reflect that.
